package com.digitaltwin.backend.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document("twin_profiles")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TwinProfile {

    @Id
    private String id;

    private String userId; // Reference to the User who owns this profile

    private String profileSummary; // Generated by AI
}
